source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

target 'JJToolKit' do
    pod 'SnapKit',                  '~> 4.2.0'  # 使用代码进行AutoLayout布局
    pod 'CryptoSwift',              '~> 1.0.0'  # 数据编码/加密
    pod 'Kingfisher',               '~> 5.5.0'  # 网络图片加载
    pod 'UICircularProgressRing',   '~> 6.2.0'  # 圆形进度条
end
